import { MetricCard } from "@/components/api-meter/metric-card";
import { EcosystemNotificationPanel } from "@/components/ecosystem/notification-panel";
import { UsageChart } from "@/components/api-meter/usage-chart";
import { apiKeys, dashboardMetrics } from "@/data/api-meter";
import { getRecentEcosystemEvents } from "@/lib/ecosystem";
import { getCurrentLocale } from "@/lib/locale";

const timeline = [
  "Luma Studio",
  "QuotePilot",
  "ReserveFlow",
  "ClientHub",
  "CommerceKit",
  "EventPass",
  "SupportDesk Lite",
  "API Meter",
];

const endpoints = [
  ["POST", "/api/ecosystem/events", "events", "99.9%", "184 ms"],
  ["GET", "/api/ecosystem/activity", "activity", "99.4%", "96 ms"],
  ["POST", "/api/usage/ingest", "usage", "98.8%", "211 ms"],
  ["GET", "/api/keys/health", "keys", "100%", "72 ms"],
];

const postReserveFlowEventTypes = new Set([
  "booking.created",
  "project.created",
  "commerce.intent.created",
  "order.created",
  "event.intent.created",
  "event.ticket.created",
  "event.checkin.completed",
  "support.context.created",
  "ticket.created",
  "ticket.resolved",
]);

const trackedModules = ["reserveflow", "clienthub", "commercekit", "eventpass", "supportdesk-lite"] as const;

const copy = {
  fr: {
    product: "Operations API / devtool",
    title: "Console d'activite de l'ecosysteme",
    intro:
      "API Meter montre la couche technique du boilerplate: logs, endpoints, latence, payloads resumes et activite generee par chaque module.",
    testTitle: "Ce que tu peux tester ici",
    receives: "Recoit",
    receivesText: "tous les events publies par les modules.",
    displays: "Affiche",
    displaysText: "action, source, cible, statut, flowId et payload.",
    demonstrates: "Demontre",
    demonstratesText: "observabilite API, journalisation et dashboard SaaS.",
    activity: "Activite de l'ecosysteme",
    logsTitle: "Logs du parcours en temps reel",
    logsText:
      "Les lignes recentes proviennent des vraies actions Luma, QuotePilot, ReserveFlow et des autres apps.",
    eventsLabel: "events",
    table: ["Date", "Flow", "Source", "Cible", "Event", "Client", "Email", "Statut", "Payload"],
    broadcast: "diffusion",
    formData: "Donnee formulaire",
    empty:
      "Aucun event pour l'instant. Demarre le parcours dans Luma Studio pour remplir ce journal.",
    health: "Sante des cles",
    active: "actives",
    timeline: "Timeline du parcours",
    endpoints: "Endpoints simules",
    scope: "portee",
    usage: "Module activity",
    usageTitle: "Evenements generes ou recus apres ReserveFlow",
    previous: "Module precedent: SupportDesk Lite",
  },
  en: {
    product: "API operations / devtool",
    title: "Ecosystem activity console",
    intro:
      "API Meter shows the technical layer of the boilerplate: logs, endpoints, latency, summarized payloads, and activity generated by every module.",
    testTitle: "What you can test here",
    receives: "Receives",
    receivesText: "every event published by the modules.",
    displays: "Displays",
    displaysText: "action, source, target, status, flowId, and payload.",
    demonstrates: "Demonstrates",
    demonstratesText: "API observability, logging, and a SaaS dashboard.",
    activity: "Ecosystem activity",
    logsTitle: "Real-time journey logs",
    logsText:
      "Recent rows come from real Luma, QuotePilot, ReserveFlow, and downstream app actions.",
    eventsLabel: "events",
    table: ["Date", "Flow", "Source", "Target", "Event", "Customer", "Email", "Status", "Payload"],
    broadcast: "broadcast",
    formData: "Form data",
    empty: "No event yet. Start the journey in Luma Studio to populate this log.",
    health: "Key health",
    active: "active",
    timeline: "Journey timeline",
    endpoints: "Simulated endpoints",
    scope: "scope",
    usage: "Module activity",
    usageTitle: "Events generated or received after ReserveFlow",
    previous: "Previous module: SupportDesk Lite",
  },
} as const;

function payloadSummary(payload: unknown) {
  if (typeof payload !== "object" || payload === null) return "No payload";
  const entries = Object.entries(payload as Record<string, unknown>).slice(0, 3);
  if (entries.length === 0) return "Empty payload";
  return entries.map(([key, value]) => `${key}: ${String(value).slice(0, 28)}`).join(" / ");
}

export default async function DashboardPage() {
  const events = await getRecentEcosystemEvents(14);
  const locale = await getCurrentLocale();
  const t = copy[locale];
  const journeyEvents = events.filter((event) => postReserveFlowEventTypes.has(event.eventType));
  const moduleActivity = trackedModules.map((module) => ({
    module,
    generated: journeyEvents.filter((event) => event.sourceApp === module).length,
    received: journeyEvents.filter((event) => event.targetApp === module).length,
  }));

  return (
    <main className="bg-[radial-gradient(circle_at_top_left,#dff7f1,transparent_32%),linear-gradient(180deg,#f7fafc_0%,#edf6f5_100%)] px-6 py-10 text-foreground">
      <div className="mx-auto max-w-6xl">
        <div className="mb-8 grid gap-6 lg:grid-cols-[1fr_0.9fr] lg:items-end">
          <div>
            <p className="inline-flex rounded-md border border-teal-200 bg-white/80 px-2.5 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-teal-700">
              KV Portfolio Ecosystem - Demo Mode
            </p>
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">
              {t.product}
            </p>
            <h1 className="mt-3 text-3xl font-semibold tracking-normal">
              {t.title}
            </h1>
            <p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">
              {t.intro}
            </p>
          </div>
          <section className="grid gap-3 rounded-lg border border-teal-200 bg-white/85 p-4 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
              {t.testTitle}
            </p>
            <div className="grid gap-2 text-sm">
              <p><span className="font-semibold">{t.receives}:</span> {t.receivesText}</p>
              <p><span className="font-semibold">{t.displays}:</span> {t.displaysText}</p>
              <p><span className="font-semibold">{t.demonstrates}:</span> {t.demonstratesText}</p>
            </div>
          </section>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {dashboardMetrics.map((metric) => (
            <MetricCard
              key={metric.label}
              label={metric.label}
              value={metric.value}
              change={metric.change}
            />
          ))}
        </div>

        <div className="mt-8">
          <EcosystemNotificationPanel appKey="api-meter" />
        </div>

        <section className="mt-8 rounded-lg border border-border bg-[#0b1220] p-5 text-white shadow-sm">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-teal-200">{t.activity}</p>
              <h2 className="mt-2 text-xl font-semibold">{t.logsTitle}</h2>
              <p className="mt-1 text-sm text-white/60">
                {t.logsText}
              </p>
            </div>
            <span className="rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold">
              {journeyEvents.length} {t.eventsLabel}
            </span>
          </div>
          <div className="mt-5 overflow-hidden rounded-md border border-white/10">
            <table className="w-full min-w-[1040px] text-left text-sm">
              <thead className="bg-white/5 text-xs uppercase tracking-[0.12em] text-white/50">
                <tr>
                  {t.table.map((label) => (
                    <th key={label} className="px-4 py-3 font-medium">{label}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-white/10">
                {journeyEvents.map((event) => (
                  <tr key={event.id} className="bg-[#0f172a]/80">
                    <td className="px-4 py-3 text-xs text-white/55">{new Date(event.createdAt).toLocaleString(locale === "fr" ? "fr-CA" : "en-CA")}</td>
                    <td className="px-4 py-3 font-mono text-[11px] text-white/45">{event.flowId}</td>
                    <td className="px-4 py-3 font-medium">{event.sourceApp}</td>
                    <td className="px-4 py-3 text-white/70">{event.targetApp ?? t.broadcast}</td>
                    <td className="px-4 py-3 font-mono text-xs text-teal-200">{event.eventType}</td>
                    <td className="px-4 py-3 text-white/70">{event.customerName ?? t.formData}</td>
                    <td className="px-4 py-3 text-white/55">{event.customerEmail ?? "-"}</td>
                    <td className="px-4 py-3 text-white/55">{event.status}</td>
                    <td className="px-4 py-3 text-xs text-white/55">{payloadSummary(event.payload)}</td>
                  </tr>
                ))}
                {journeyEvents.length === 0 ? (
                  <tr>
                    <td colSpan={9} className="px-4 py-8 text-center text-sm text-white/55">
                      {t.empty}
                    </td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>
        </section>

        <div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
          <UsageChart />
          <section className="border border-border bg-card p-5 shadow-sm">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">{t.health}</h2>
              <span className="border border-border bg-background px-2.5 py-1 text-xs font-medium">
                126 {t.active}
              </span>
            </div>
            <div className="mt-6 grid gap-3">
              {apiKeys.map((key) => (
                <article key={key.prefix} className="border border-border bg-background p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <h3 className="font-medium">{key.name}</h3>
                      <p className="mt-1 font-mono text-xs text-muted-foreground">
                        {key.prefix}
                      </p>
                    </div>
                    <span className="text-xs font-medium text-teal-700">{key.status}</span>
                  </div>
                  <div className="mt-4 flex flex-wrap gap-2">
                    {key.scopes.map((scope) => (
                      <span
                        key={scope}
                        className="border border-border bg-card px-2 py-1 font-mono text-xs"
                      >
                        {scope}
                      </span>
                    ))}
                  </div>
                </article>
              ))}
            </div>
          </section>
        </div>

        <div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
          <section className="rounded-lg border bg-card p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
              {t.timeline}
            </p>
            <div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold">
              {timeline.map((item, index) => (
                <span key={item} className={index === 7 ? "rounded-md bg-primary px-3 py-2 text-primary-foreground" : "rounded-md border bg-background px-3 py-2"}>
                  {String(index + 1).padStart(2, "0")} {item}
                </span>
              ))}
            </div>
          </section>
          <section className="rounded-lg border bg-card p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
              {t.endpoints}
            </p>
            <div className="mt-4 grid gap-3">
              {endpoints.map(([method, path, scope, success, latency]) => (
                <div key={path} className="grid gap-3 rounded-md border bg-background p-3 text-sm sm:grid-cols-[4rem_1fr_4rem_4rem]">
                  <span className="font-mono text-xs font-semibold text-teal-700">{method}</span>
                  <span className="font-mono text-xs">{path}</span>
                  <span>{success}</span>
                  <span>{latency}</span>
                  <span className="text-xs text-muted-foreground sm:col-span-4">{t.scope}: {scope}</span>
                </div>
              ))}
            </div>
          </section>
        </div>

        <section className="mt-8 rounded-lg border bg-card p-5 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
                {t.usage}
              </p>
              <h2 className="mt-2 text-lg font-semibold">{t.usageTitle}</h2>
            </div>
            <a href="https://supportdesk-lite-jet.vercel.app" className="rounded-md bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">
              {t.previous}
            </a>
          </div>
          <div className="mt-5 grid gap-3 md:grid-cols-2">
            {moduleActivity.map(({ module, generated, received }) => {
              const total = generated + received;
              const width = `${Math.min(100, Math.max(8, total * 18))}%`;
              return (
              <div key={module} className="rounded-md border bg-background p-4">
                <div className="flex items-center justify-between gap-3 text-sm">
                  <span className="font-semibold">{module}</span>
                  <span className="font-mono text-xs text-muted-foreground">out {generated} / in {received}</span>
                </div>
                <div className="mt-3 h-2 rounded-full bg-muted">
                  <div className="h-2 rounded-full bg-primary" style={{ width }} />
                </div>
              </div>
              );
            })}
          </div>
        </section>
      </div>
    </main>
  );
}
